### PR TITLE
Tripal eutils.module.fix

### PR DESCRIPTION
**Pull request by dsenalik**
Pull request for Issue #228 

The missing parameter (an empty array) is added to the call to tripal_report_error()

### CODE REVIEW

**Comment by dsenalik** [comment]
Sorry for the mess of commits, there is only one small change actually made

**Comment by dsenalik** [comment]
I added a second change to define a default assembly method is none was specified, needed because there is a NOT NULL constraint on the ```program``` and ```programversion``` columns in the ```chado.analysis``` table.
This problem showed up on NCBI assembly GCA_902728035.1 which is what triggered my discovery of the first error.

**Comment by mpoelchau** [comment]
Thanks @dsenalik, I think the placeholder text that you added is good. The next question would be how to work with NCBI and the submitters to add a method, but that's out of scope of this module...

Thanks for submitting the PR!

**Comment by dsenalik** [comment]
Check has failed on a request to NCBI. I am occasionally getting timeouts locally. Maybe we can rerun the checks again later?

1) Tests\EUtilsTest::testConvertingAccession with data set #5 ('biosample', 'SAMN02981385', '2981385')
Exception: ERROR Could not make request: Status: 400

**Pull request merged**
